### PR TITLE
add more common patterns

### PR DESCRIPTION
**Pull request by Synoon**
add more common patterns

### CODE REVIEW

**Comment by Synoon** [comment]
@robindijkhof hei could you maybe accept the PR? would be nice for other users I guess

**Comment by robindijkhof** [comment]
I need to test it. I hope I got some time saturday.

**Comment by robindijkhof** [comment]
@Synoon I don't think i can merge this. My problem is with the todo keyword. I think it is possible to have a multi line/paragraph todo. For example:

    1. Some text. \todo{ this is a long todo line that not just only takes multiple 
       multiple lines but also has new lines.
    2. This is just after the newline.}

This example would be replace by

    1. Some text. 

Problem is, the number of lines in the new text and the oldtext are not equal. This is a requirement, which I cannot do anything about. The same may apply to the `mbox`. I am not sure though,  I do not know mbox.

**Comment by robindijkhof** [comment]
https://github.com/robindijkhof/overleaf-textarea/issues/22 might provide a soltion for the problem stated above

**Pull request closed without merging**
